"""Export the 840-slot climatology results to CSV + markdown.
Reads results/climatology_diffused_840.json and writes:
  - results/climatology_diffused_840.csv        (one row per slot)
  - results/climatology_diffused_840_REPORT.md  (human-readable report)
"""
import json
import random
from collections import defaultdict
from datetime import datetime
from pathlib import Path

import sys
sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
import config
from core.io import load_popularity_npz

R = config.PROJECT_ROOT / "results"
J = R / "climatology_diffused_840.json"
CSV = R / "climatology_diffused_840.csv"
MD = R / "climatology_diffused_840_REPORT.md"

SMOOTH_NPZ = str(config.DATA_DIR / "popularity_results_smoothed_osm_gamma020.npz")
GRAPH_JSON = str(config.GRAPH_FILE)
SEED = 7
BPW = 120

# Re-derive the slot list deterministically (same code as the runner) so
# we can label each row of the CSV with (weekday, hour, minute, target_date).
b = load_popularity_npz(SMOOTH_NPZ)
times = [str(t) for t in b["times"]]
slot_to_times = defaultdict(list)
for t in times:
    dt = datetime.strptime(t, "%Y-%m-%d %H:%M:%S")
    slot_to_times[(dt.weekday(), dt.hour, dt.minute)].append(t)
for s in slot_to_times:
    slot_to_times[s].sort()
full_slots = {s: ts for s, ts in slot_to_times.items() if len(ts) >= 4}
by_wd = defaultdict(list)
for s in full_slots.keys():
    by_wd[s[0]].append(s)
rng = random.Random(SEED)
sampled = []
for wd in range(7):
    pool = by_wd[wd]
    rng.shuffle(pool)
    sampled.extend(pool[:BPW])

d = json.load(open(J))
top = d["top100_per_slot"]
ov  = d["overall_per_slot"]
assert len(sampled) == len(top) == len(ov), \
    f"{len(sampled)} vs {len(top)} vs {len(ov)}"

WD = ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"]
with open(CSV, "w") as f:
    f.write("idx,weekday,wd_name,hour,minute,week1,week2,week3,week4,top100_mre,overall_mre\n")
    for i, s in enumerate(sampled):
        ts = full_slots[s][:4]
        wd, h, m = s
        f.write(f"{i},{wd},{WD[wd]},{h},{m:02d},"
                f"{ts[0]},{ts[1]},{ts[2]},{ts[3]},"
                f"{top[i]:.6f},{ov[i]:.6f}\n")
print(f"saved {CSV}")

with open(MD, "w") as f:
    f.write("# Climatology on diffused data, 840 slots\n\n")
    f.write("## Setup\n\n")
    f.write("- **Data file**: `popularity_results_smoothed_osm_gamma020.npz` (the\n")
    f.write("  γ=0.20 diffused popularity prior, 8640 5-min bins × 99,716 links).\n")
    f.write("- **Slots**: 7 weekdays × 120 random (hour, minute) slots per weekday = **840 slots**, "
            f"seed={SEED}.\n")
    f.write("- **Per slot**: history = mean of the diffused $E_b$ vectors at the\n")
    f.write("  3 chronologically-first weeks of that slot; target = diffused\n")
    f.write("  $E_b$ at the 4th week of that slot (the 5th occurrence on\n")
    f.write("  Sat/Sun is dropped).\n")
    f.write(f"- **MRE per slot**: $|t-p| / (t + \\varepsilon)$ with $\\varepsilon = 10^{{-6}}$,\n")
    f.write("  aggregated two ways:\n")
    f.write("  - **Top-100 MRE**: mean over the 100 highest-traffic links of the target;\n")
    f.write("  - **Overall MRE**: mean over all 99,716 links.\n\n")
    f.write("## Aggregate stats (over 840 slots)\n\n")
    f.write("| stat | Top-100 MRE | Overall MRE |\n")
    f.write("|---|---|---|\n")
    for k in ["mean", "median", "std", "p05", "p25", "p75", "p95", "min", "max"]:
        f.write(f"| {k} | {d['top100'][k]:.4f} | {d['overall'][k]:.4f} |\n")
    f.write("\n## Histograms\n\n")
    f.write("![histograms](climatology_diffused_840_hist.pdf)\n\n")
    f.write("## Files\n\n")
    f.write("- `climatology_diffused_840.json` — all stats + per-slot arrays (840 + 840)\n")
    f.write("- `climatology_diffused_840.csv` — one row per slot with weekday, time, calendar dates of the 4 weeks, and the two MRE values\n")
    f.write("- `climatology_diffused_840_hist.pdf` — the two histograms\n\n")
    f.write("## Reproducibility\n\n")
    f.write("Generated by `analysis/climatology_diffused_840.py`. Re-run with:\n\n")
    f.write("```\npython3 analysis/climatology_diffused_840.py\n```\n")
print(f"saved {MD}")
